modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
[[mods]]
modId="assembly"
version="1.0.0"
displayName="Assembly"
logoFile= "icon.png"
credits="Uraneptus for helping me with the tags"
authors="Evoslab"
description='''
Expands on 1.18.1 Blocks!
'''

[[dependencies.assembly]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.assembly]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1)"
    ordering="NONE"
    side="BOTH"
[[dependencies.assembly]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[5.0.0,)"
    ordering = "BEFORE"
    side = "BOTH"

[modproperties.assembly]
    catalogueImageIcon= "icon.png"
