modLoader="javafml" #mandatory
loaderVersion="[37,)"
license="MIT"
[[mods]] #mandatory
modId="assembly" #mandatory
version="1.0.0" #mandatory
displayName="Assembly" #mandatory
logoFile= "icon.png" #optional
authors="Evoslab" #optional
description='''
Expands on 1.17 Blocks!
'''

[[dependencies.assembly]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.assembly]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
