modLoader="javafml"
loaderVersion="[37,)"
license="MIT"
[[mods]]
modId="assembly"
version="1.0.0"
displayName="Assembly"
logoFile= "icon.png"
credits="Uraneptus for helping me with the tags"
authors="Evoslab"
description='''
Expands on 1.17 Blocks!
'''

[[dependencies.assembly]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.assembly]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
[[dependencies.assembly]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[4.0.1,)"
    ordering = "BEFORE"
    side = "BOTH"

[modproperties.assembly]
    catalogueImageIcon= "icon.png"
